language: csharp

matrix:
  include:
    - os: linux
      dist: xenial
      dotnet: 2.2.401
      mono: none

script:
  - dotnet restore
  - dotnet build -f netstandard2.0 -c Release src/Orion/Orion.csproj
  - dotnet test -f netcoreapp2.2 -c Release tests/Orion.Tests/Orion.Tests.csproj
