name: dotnet-core

on:
  push:
    branches: [ v1.4 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: Set up .NET core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300
      - name: Run tests (with code coverage)
        run: |
          dotnet build -f netstandard2.1 -c Debug src/Orion/Orion.csproj
          dotnet test -f netcoreapp3.1 -c Debug tests/Orion.Tests/Orion.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: tests/Orion.Tests/coverage.cobertura.xml
