name: dotnet-core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: Set up .NET core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300
      - name: Run tests (with code coverage)
        run: dotnet test -f netcoreapp3.1 -c Release tests/Orion.Core.Tests/Orion.Core.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: tests/Orion.Core.Tests/coverage.cobertura.xml
      - name: Build artifacts
        run: dotnet publish -f netstandard2.1 -c Release src/Orion.Core/Orion.Core.csproj
      - name: Publish artifacts
        uses: actions/upload-artifact@master
        with:
          name: Orion.Core
          path: src/Orion.Core/bin/Release/netstandard2.1/publish
