name: tests

on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Running tests...
        run: |
          dotnet build -f netstandard2.1 -c Release src/Orion/Orion.csproj
          dotnet test -f netcoreapp3.0 -c Release tests/Orion.Tests/Orion.Tests.csproj
